-- SQLite
INSERT INTO BOOK (title, author, language, pages, quantity) VALUES
("The Great Gatsby", "F. Scott Fitzgerald", "English", 218, 10),
("To Kill a Mockingbird", "Harper Lee", "English", 281, 15),
("1984", "George Orwell", "English", 328, 20),
("Pride and Prejudice", "Jane Austen", "English", 279, 12),
("The Catcher in the Rye", "J.D. Salinger", "English", 234, 8),
("Animal Farm", "George Orwell", "English", 112, 22),
("The Hobbit", "J.R.R. Tolkien", "English", 310, 14),
("Lord of the Flies", "William Golding", "English", 182, 18),
("The Grapes of Wrath", "John Steinbeck", "English", 464, 5),
("Brave New World", "Aldous Huxley", "English", 288, 11),
("The Sound and the Fury", "William Faulkner", "English", 326, 9),
("The Scarlet Letter", "Nathaniel Hawthorne", "English", 238, 7),
("The Adventures of Huckleberry Finn", "Mark Twain", "English", 366, 16),
("The Picture of Dorian Gray", "Oscar Wilde", "English", 304, 13),
("The Lord of the Rings", "J.R.R. Tolkien", "English", 1178, 6),
("A Tale of Two Cities", "Charles Dickens", "English", 489, 4),
("Dracula", "Bram Stoker", "English", 418, 3),
("The Odyssey", "Homer", "English", 541, 2),
("The Brothers Karamazov", "Fyodor Dostoevsky", "Russian", 824, 10),
("War and Peace", "Leo Tolstoy", "Russian", 1440, 5),
("Crime and Punishment", "Fyodor Dostoevsky", "Russian", 430, 7),
("Anna Karenina", "Leo Tolstoy", "Russian", 864, 9),
("The Idiot", "Fyodor Dostoevsky", "Russian", 656, 6),
("One Hundred Years of Solitude", "Gabriel Garcia Marquez", "Spanish", 417, 12),
("Don Quixote", "Miguel de Cervantes", "Spanish", 992, 8),
("Love in the Time of Cholera", "Gabriel Garcia Marquez", "Spanish", 368, 4),
("The Old Man and the Sea", "Ernest Hemingway", "English", 127, 11),
("Moby Dick", "Herman Melville", "English", 625, 15),
("The Divine Comedy", "Dante Alighieri", "Italian", 432, 3),
("Les Misérables", "Victor Hugo", "French", 1463, 6),
("The Stranger", "Albert Camus", "French", 123, 8),
("Candide", "Voltaire", "French", 129, 4),
("Madame Bovary", "Gustave Flaubert", "French", 368, 2),
("The Plague", "Albert Camus", "French", 278, 7),
("The Three Musketeers", "Alexandre Dumas", "French", 704, 3),
("Gulliver's Travels", "Jonathan Swift", "English", 306, 9),
("Wuthering Heights", "Emily Bronte", "English", 337, 11),
("Jane Eyre", "Charlotte Bronte", "English", 532, 14),
("Great Expectations", "Charles Dickens", "English", 544, 10),
("Frankenstein", "Mary Shelley", "English", 280, 8),
("The Adventures of Tom Sawyer", "Mark Twain", "English", 276, 6),
("The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "English", 307, 12),
("Sense and Sensibility", "Jane Austen", "English", 335, 5),
("The Canterbury Tales", "Geoffrey Chaucer", "English", 524, 7),
("The War of the Worlds", "H.G. Wells", "English", 288, 4),
("The Time Machine", "H.G. Wells", "English", 118, 6),
("Heart of Darkness", "Joseph Conrad", "English", 78, 9),
("The Call of the Wild", "Jack London", "English", 128, 7),
("The Hound of the Baskervilles", "Arthur Conan Doyle", "English", 190, 3),
("The Count of Monte Cristo", "Alexandre Dumas", "French", 1276, 5),
("Around the World in Eighty Days", "Jules Verne", "French", 192, 8),
("The Mysterious Island", "Jules Verne", "French", 607, 10),
("The Adventures of Pinocchio", "Carlo Collodi", "Italian", 188, 2),
("Robinson Crusoe", "Daniel Defoe", "English", 320, 15),
("Little Women", "Louisa May Alcott", "English", 759, 12),
("The Secret Garden", "Frances Hodgson Burnett", "English", 306, 6),
("Anne of Green Gables", "L.M. Montgomery", "English", 320, 4),
("The Wind in the Willows", "Kenneth Grahame", "English", 256, 7),
("The Jungle Book", "Rudyard Kipling", "English", 308, 9),
("The Adventures of Robin Hood", "Howard Pyle", "English", 288, 3),
("Black Beauty", "Anna Sewell", "English", 245, 8),
("Treasure Island", "Robert Louis Stevenson", "English", 204, 5),
("The Swiss Family Robinson", "Johann David Wyss", "German", 352, 11),
("Heidi", "Johanna Spyri", "German", 288, 9),
("The Adventures of Tintin", "Hergé", "French", 192, 7),
("The Chronicles of Narnia", "C.S. Lewis", "English", 768, 6),
("The Hobbit", "J.R.R. Tolkien", "English", 310, 4),
("The Lord of the Rings", "J.R.R. Tolkien", "English", 1178, 3),
("Harry Potter and the Philosopher's Stone", "J.K. Rowling", "English", 223, 20),
("Harry Potter and the Chamber of Secrets", "J.K. Rowling", "English", 251, 18),
("Harry Potter and the Prisoner of Azkaban", "J.K. Rowling", "English", 317, 15),
("Harry Potter and the Goblet of Fire", "J.K. Rowling", "English", 636, 12),
("Harry Potter and the Order of Phoenix", "J.K. Rowling", "English", 766, 8),
("Harry Potter and the Half Blood Prince", "J.K. Rowling", "English", 607, 6),
("Harry Potter and the Deathly Hallows", "J.K. Rowling", "English", 607, 4),
("The Hunger Games", "Suzanne Collins", "English", 374, 14),
("Catching Fire", "Suzanne Collins", "English", 391, 11),
("Mockingjay", "Suzanne Collins", "English", 390, 8),
("Divergent", "Veronica Roth", "English", 487, 6),
("Insurgent", "Veronica Roth", "English", 525, 4),
("Allegiant", "Veronica Roth", "English", 526, 2),
("The Fault in Our Stars", "John Green", "English", 313, 9),
("Looking for Alaska", "John Green", "English", 221, 6),
("Paper Towns", "John Green", "English", 305, 4),
("The Da Vinci Code", "Dan Brown", "English", 481, 12),
("Angels and Demons", "Dan Brown", "English", 620, 9),
("Inferno", "Dan Brown", "English", 461, 7),
("The Girl with the Dragon Tattoo", "Stieg Larsson", "Swedish", 672, 10),
("The Girl Who Played with Fire", "Stieg Larsson", "Swedish", 724, 7),
("The Girl Who Kicked the Hornets' Nest", "Stieg Larsson", "Swedish", 656, 4),
("The Catcher in the Rye", "J.D. Salinger", "English", 234, 8),
("To Kill a Mockingbird", "Harper Lee", "English", 281, 11),
("1984", "George Orwell", "English", 328, 14),
("Animal Farm", "George Orwell", "English", 112, 9),
("The Hitchhiker's Guide to the Galaxy", "Douglas Adams", "English", 193, 6),
("Brave New World", "Aldous Huxley", "English", 288, 5),
("Fahrenheit 451", "Ray Bradbury", "English", 158, 7),
("The Martian Chronicles", "Ray Bradbury", "English", 222, 3),
("The Handmaid's Tale", "Margaret Atwood", "English", 311, 5),
("The Great Gatsby", "F. Scott Fitzgerald", "English", 180, 9),
("Of Mice and Men", "John Steinbeck", "English", 107, 6),
("The Pearl", "John Steinbeck", "English", 96, 4),
("The Old Man and the Sea", "Ernest Hemingway", "English", 127, 7),
("For Whom the Bell Tolls", "Ernest Hemingway", "English", 471, 3),
("The Sun Also Rises", "Ernest Hemingway", "English", 178, 5),
("A Farewell to Arms", "Ernest Hemingway", "English", 352, 2),
("One Hundred Years of Solitude", "Gabriel Garcia Marquez", "Spanish", 417, 11),
("Love in the Time of Cholera", "Gabriel Garcia Marquez", "Spanish", 348, 7),
("The Picture of Dorian Gray", "Oscar Wilde", "English", 254, 6),
("The Importance of Being Earnest", "Oscar Wilde", "English", 76, 4),
("Pride and Prejudice", "Jane Austen", "English", 279, 10),
("Sense and Sensibility", "Jane Austen", "English", 304, 6),
("Emma", "Jane Austen", "English", 474, 4),
("Frankenstein", "Mary Shelley", "English", 280, 8),
("Dracula", "Bram Stoker", "English", 418, 7),
("The Adventures of Tom Sawyer", "Mark Twain", "English", 193, 9),
("The Adventures of Huckleberry Finn", "Mark Twain", "English", 366, 7),
("Little Women", "Louisa May Alcott", "English", 759, 5),
("The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", "C.S. Lewis", "English", 206, 10),
("The Chronicles of Narnia: Prince Caspian", "C.S. Lewis", "English", 216, 8),
("The Chronicles of Narnia: The Voyage of the Dawn Treader", "C.S. Lewis", "English", 248, 6),
("The Chronicles of Narnia: The Silver Chair", "C.S. Lewis", "English", 240, 4),
("The Chronicles of Narnia: The Horse and His Boy", "C.S. Lewis", "English", 224, 2),
("The Chronicles of Narnia: The Magician's Nephew", "C.S. Lewis", "English", 221, 1),
("The Chronicles of Narnia: The Last Battle", "C.S. Lewis", "English", 228, 1),
("The Lord of the Rings: The Fellowship of the Ring", "J.R.R. Tolkien", "English", 398, 12),
("The Lord of the Rings: The Two Towers", "J.R.R. Tolkien", "English", 327, 10),
("The Lord of the Rings: The Return of the King", "J.R.R. Tolkien", "English", 455, 8),
("The Hobbit", "J.R.R. Tolkien", "English", 310, 7),
("The Silmarillion", "J.R.R. Tolkien", "English", 365, 4),
("The Name of the Wind", "Patrick Rothfuss", "English", 662, 6),
("The Wise Man's Fear", "Patrick Rothfuss", "English", 994, 3),
("The Hunger Games: The Ballad of Songbirds and Snakes", "Suzanne Collins", "English", 517, 2),
("The Chronicles of Narnia: The Magician's Nephew", "C.S. Lewis", "English", 221, 1),
("The Girl with the Dragon Tattoo", "Stieg Larsson", "Swedish", 672, 10),
("The Girl Who Played with Fire", "Stieg Larsson", "Swedish", 724, 7)

;
